services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://weather_user:weather_pass@db:5432/weather_ai
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=change-me-in-prod
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY:-}
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=weather_ai
      - POSTGRES_USER=weather_user
      - POSTGRES_PASSWORD=weather_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata: {}
